#!/bin/bash
cd ../data
chmod +x ../data/surprise.php
nb=$(../data/surprise.php);
tr -d '"' < ../data/tableau.csv | sort -t ',' -k 4 -k 5 -k 6 -rn -k 2 > ../data/tableau2.csv 
nb=$(../data/surprise2.php);
ab=$(php ../data/geneHTML.php);